### ISSUE TITLE
A more realistic sample is needed

### ISSUE THREAD

**Issue by albertwoo** [dbrattli/Elmish.Streams#5]
I try to play with this library, but I did not know how to deal with multiple pages or components.
Like in the AutoComplete sample, how can I compose the AutoComplete component with other component? How to compose those query elegantly?
Thanks!

**Comment by dbrattli** [comment]
Thanks for the feedback. I have't looked much into scalability yet, but it should be easier now after watching Scaling Elmish Applications by Zaid Ajaj at Fableconf. There are also changes coming that will make it possible to have different queries depending on the model, thus separate pages can have separate queries etc.

**Comment by dbrattli** [comment]
You can now check out the Magic example for how to compose streams. Streams are different from queries in that they can be changed based on the current model: https://github.com/dbrattli/Elmish.Streams/tree/master/examples/Magic

**Comment by albertwoo** [comment]
Thanks, will try :)

**Comment by dbrattli** [comment]
AutoComplete now rewritten as a component. Components are symmetric in the sense that a component does not really know if it's the main application, a component or a sub-component. https://github.com/dbrattli/Elmish.Streams/tree/master/examples/Autocomplete/src/Client
